// <auto-generated />
using System;
using Habeas.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Habeas.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HabeasDbContext))]
    partial class HabeasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Habeas.Domain.Users.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_user_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("TelegramUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_telegram_user_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Habeas.Domain.Users.UserProfile", b =>
                {
                    b.OwnsOne("Habeas.Domain.Users.BodyMetrics", "BodyMetrics", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<double>("HeightCm")
                                .HasColumnType("double precision")
                                .HasColumnName("body_metrics_height_cm");

                            b1.Property<double>("WeightKg")
                                .HasColumnType("double precision")
                                .HasColumnName("body_metrics_weight_kg");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.Navigation("BodyMetrics");
                });
#pragma warning restore 612, 618
        }
    }
}
